### PR TITLE
QPPA-924: Adding example XML schemas

### PR DESCRIPTION
**Pull request by samskeller**
This PR adds example XML schemas for the Submission, MeasurementSet, Measurement, and Benchmark resource representation within the developer documentation. These schemas are combined with the JSON schemas via react-tabs, consistent with how we do similar tab groupings elsewhere on the developer documentation. Also slightly cleaned up and standardized how we represent arrays of objects within these schemas (using parentheses rather than brackets (which we use for showing a range of options, like with the "value" property of the Measurement model) or greater than/less than symbols, which looks confusing with XML)

Example:
devdocsxmlschema

Test Plan:
* [ ] Automated tests should pass

Associated JIRA issues:
* https://jira.cms.gov/browse/QPPA-924

Reviewers: @marimiyachi @kalvinwang  @abarciauskas-bgse

### CODE REVIEW

**Comment by samskeller** [comment]
Hmm not sure why one test failed -- it passes for me locally... will look into this a bit

**Comment by samskeller** [comment]
Test failures have been fixed by merging in the latest from `master`, which has different tests that no longer fail!

**Comment by abarciauskas-bgse** [comment]
@samskeller wonder what your thoughts are on making these component files more succinct via a new `<SchemaTabPanel />` class that had properties for content-type and object type, and the schema-tab-panel class could maintain all the example content. e.g.:

```javascript
<Tabs className='technical-details-pane'>
  <TabList>
    <Tab>JSON</Tab>
    <Tab>XML</Tab>
  </TabList>
  <SchemaTabPanel content-type="json" object-type="benchmark" />
  <SchemaTabPanel content-type="xml" object-type="benchmark" />
</Tabs>
```

Just a thought - it looks like `DataModelTable` is another model where the `FIELDS` content still lives in the component schema but is not nested within the component structure.

**Comment by samskeller** [comment]
@abarciauskas-bgse hmm actually, looking at this more, I'm not totally sure what would be a good change here. I don't see a great way to create a `SchemaTabPanel` that can take, as an argument, the content inside, because sometimes we want the content to be just a string but sometimes we want it to be two strings with HTML between them (like when there's a link to another model in there). So then the only reason to put this stuff in a new file would be to make the schema files shorter, but that kinda spreads out the places where we define the schemas (like we'd have the `FIELDS` stuff in one file but the JSON/XML schemas in another file, which is harder to cleanup if we change the schema). 

If you can see a good way to be more DRY here, lemme know, but otherwise I kinda think spreading out the schemas would be more confusing than helpful 🤷‍♂️ . WDYT?

**Pull request closed without merging**
